dataset:
  dataset_size: null
  interface_distance_threshold: 5
  interface_exclusion_threshold: 2
  lig_box_padding: 8
  lig_elements:
  - C
  - N
  - O
  - S
  - P
  - F
  - Cl
  - Br
  - I
  - B
  location: data/bindingmoad_processed/
  max_fake_atom_frac: 0.0
  min_ligand_atoms: 8
  pocket_cutoff: 8
  rec_elements:
  - C
  - N
  - O
  - S
  - P
  - F
  - Cl
  - Br
  - I
  - B
  remove_hydrogen: true
diffusion:
  lig_feat_norm_constant: 1
  n_timesteps: 1000
  precision: 1.0e-05
  rl_dist_threshold: 0
dynamics:
  hidden_nf: 256
  kl_k: 5
  ll_k: 0
  message_norm: 0.0
  n_layers: 6
  no_cg: false
  norm: true
  update_kp_feat: true
  use_tanh: true
experiment:
  name: distinctive-wood-43526
  results_dir: sweep_runs/single_runs
graph:
  graph_cutoffs:
    kk: 8
    kl: 8
    ll: 5
    rk: 100
    rr: 3.5
  n_keypoints: 40
rec_encoder:
  coords_range: 10
  fix_pos: false
  hidden_n_node_feat: 128
  in_n_node_feat: 10
  k_closest: 5
  kp_feat_scale: 1.0
  kp_rad: 0.0
  message_norm: 0.0
  n_convs: 4
  n_kk_convs: 0
  n_kk_heads: 4
  no_cg: false
  norm: true
  out_n_node_feat: 128
  use_sameres_feat: true
  use_tanh: true
rec_encoder_loss:
  loss_type: optimal_transport
  use_interface_points: true
reconstruction:
  n_lig_feat: 10
  n_rec_atom_feat: 10
sampling_config:
  diff_batch_size: 128
  n_receptors: 10
  n_replicates: 12
  rec_enc_batch_size: 128
training:
  batch_size: 64
  clip_grad: true
  clip_value: 1.5
  epochs: 1000
  learning_rate: 0.0001
  num_workers: 4
  rec_encoder_loss_weight: 0.1
  rl_hinge_loss_weight: 0
  sample_interval: 30
  save_interval: 30
  scheduler:
    rec_enc_weight_decay_midpoint: 0
    rec_enc_weight_decay_scale: 0.25
    restart_interval: 0
    restart_type: cosine
    warmup_length: 1
  test_epochs: 3
  test_interval: 1
  train_metrics_interval: 0.1
  weight_decay: 1.0e-12
wandb:
  init_kwargs:
    group: refactor2_sweep
    mode: online
    name: null
    project: ligdiff_cluster
  watch_kwargs:
    log: null
    log_freq: 100
  watch_model: false
