experiment:
  name: baseline_clipping
  results_dir: experiments/

wandb:
  init_kwargs:
    mode: online # options: online, offline, disabled
    project: ligdiff
    group: 
  watch_model: False
  watch_kwargs:
    log: all # (str) One of "gradients", "parameters", "all", or None
    log_freq: 1000 # (int) log gradients and parameters every N batches

dataset:
  location: 'data/crossdock_50k/'
  rec_elements: ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'B'] # ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'Mg', 'Mn', 'Zn', 'Ca', 'Fe', 'B']
  lig_elements: ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'B']
  remove_hydrogen: True
  min_ligand_atoms: 8 # minimum number of atoms in a ligand, skip all smaller ligands in the dataset when processing
  pocket_edge_algorithm: 'bruteforce-blas'
  lig_box_padding: 8 # angstroms
  pocket_cutoff: 5 # angstroms
  receptor_k: 8
  dataset_size: 50000 # used only for debugging
  use_boltzmann_ot: False

rec_encoder:
  n_keypoints: 20
  n_convs: 6
  hidden_n_node_feat: 256 
  out_n_node_feat: 256

diffusion:
  n_timesteps: 1000

dynamics:
  n_layers: 6
  hidden_nf: 256
  receptor_keypoint_k: 6
  ligand_k: 8
  use_tanh: True # whether to use tanh activation for coordinate updates 


rec_encoder_loss:
  use_boltzmann_weights: False

training:
  rec_encoder_loss_weight: 0.1
  learning_rate: 1.0e-4
  weight_decay: 1.0e-12
  clip_grad: True
  clip_value: 1.0
  epochs: 1000
  batch_size: 32
  test_interval: 0.25 # measured in epochs
  train_metrics_interval: 0.05 # epochs
  save_interval: 2 # epoch
  test_epochs: 2 # number of epochs to run when evaluating on the test set
  num_workers: 0
  cyclic_lr: # settings regarding a cyclic learning rate
    use_cyclic_lr: False
    base_lr: 1.0e-5
    max_lr: 1.0e-4
    step_size_up_frac: 0.25 # we specify step_size_up as a fraction of iterations_per_epoch