experiment:
  name: dev
  results_dir: experiments/

dataset_location:
  train: 'data/crossdock_processed/train.pkl'
  test: 'data/crossdock_processed/test.pkl'

dataset_config:
  rec_elements: ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'B'] # ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'Mg', 'Mn', 'Zn', 'Ca', 'Fe', 'B']
  lig_elements: ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'B']
  remove_hydrogen: True
  min_ligand_atoms: 8 # minimum number of atoms in a ligand, skip all smaller ligands in the dataset when processing
  pocket_edge_algorithm: 'bruteforce-blas'
  lig_box_padding: 8 # angstroms
  pocket_cutoff: 5 # angstroms
  receptor_k: 8
  ligand_k: 3
  dataset_size: 20 # # used only for debugging
  use_boltzmann_ot: False

rec_encoder_config:
  n_keypoints: 20
  n_egnn_convs: 6
  hidden_n_node_feat: 256 
  out_n_node_feat: 256

diffusion_config:
  n_timesteps: 1000

dynamics:
  n_layers: 6
  hidden_nf: 256
  receptor_keypoint_k: 6
  ligand_k: 8
  use_tanh: True # whether to use tanh activation for coordinate updates 


rec_encoder_loss_config:
  use_boltzmann_weights: False

training_config:
  rec_encoder_loss_weight: 0.1
  learning_rate: 1.0e-4
  weight_decay: 1.0e-9
  clip_grad: True
  clip_value: 1.5
  epochs: 1
  batch_size: 32
  test_interval: 100 # measured in iterations (an iteration is one forwards/backwards pass in the training loop)
  train_metrics_interval: 100 # iterations
  save_interval: 100 # iterations (an iteration is one forwards/backwards pass in the training loop)
  test_epochs: 2 # number of epochs to run when evaluating on the test set
  num_workers: 1